### ISSUE TITLE
Cannot access flex.view in 1.3.4

### ISSUE THREAD

**Issue by SirensOfTitan** [layoutBox/FlexLayout#65] opened 2018-03-05 19:34 UTC
Per documentation:

> It is possible to access the flex items's UIView using flex.view. This is particularly useful when using flex.define() method.

1.3.4 eliminates that by making flex.view a private method alongside fixing the retain cycle issue.  This is a breaking change to the API that I don't think should be happening on a _._.z version bump.  

It's really convenient to attach an extension to Flex class to do stuff like drop shadow, borders in a chainable way--it makes view descriptions very declarative.  Would prefer that we don't make this var private -- developers can easily read the weak tag and understand the limitations there.

**Comment by SirensOfTitan** [comment] 2018-03-05 19:44
With more detail: I disagree pretty strongly with the reasoning in pull request 64.  

> Now view of Flex is hidden, because it's a weak variable, and users of Flex may brake this state. I think in practice it's rare to see Flex being cached far away from it's hosting view, so this shouldn't be a problem.

Is there any way to actually access a view in an example like:
```
flex.width(44).define { flex in 
  // How do I get the view here if we don't allow access to it? 
  flex.addItem().backgroundColor(.green).height(40).width(10)
}
```

Additionally, as I mentioned above, I add extensions to the Flex API here to do certain draw operations: layout and presentation go hand in hand, and chaining them together is really nice:
```
flex.width(44).height(50)
  .dropShadow(color: .black, offset: CGSize(width: 0, height: 0), radius: 4)
  .roundedCorners(corners: .allCorners, radius: 5)
```
```

**Comment by Rag0n** [comment] 2018-03-05 19:49
I think it is just a bug. View should be declared as public readonly property. Currently setter is private and getter is internal.

**Comment by SirensOfTitan** [comment] 2018-03-05 19:52
> I think it is just a bug. View should be declared as public readonly property. Currently setter is private and getter is internal.

Yeah, I think this was just an overlook, but best to justify my viewpoint here just so a good discussion occurs. :)  It seems like the PR intentionally eliminated view from public access, and perhaps PR was accepted without noticing this, as the 1.3.4 documentation still refers to flex.view.

**Comment by lucdion** [comment] 2018-03-05 21:13
Hi @SirensOfTitan, in fact the PR suggest that, but this has been changed. See comments in https://github.com/layoutBox/FlexLayout/pull/64.

In fact the 'flex.view' property is now a weak reference instead of a strong reference, which was causing circular references. You can still access it using something like `flex.view?.alpha = 0.8`

The documentation has also been updated, see https://github.com/layoutBox/FlexLayout#accessing-flex-items-uiview.

For the `flex` class being final, maybe we should keep it as it was before until we have stats that prove that it really affects performances, which is not clear from what I've read on the Internet. This was an issue with older xcode releases, but it seams that this is not the case anymore. 
Any comment @Rag0n on this?

By the way @SirensOfTitan, it is really nice your add-on for shadows and roundedCorners. If you share your extension source code, I would be more than happy to add it into FlexLayout.

```
flex.width(44).height(50)
  .dropShadow(color: .black, offset: CGSize(width: 0, height: 0), radius: 4)
  .roundedCorners(corners: .allCorners, radius: 5)
```

**Comment by lucdion** [comment] 2018-03-06 13:57
@SirensOfTitan @Rag0n, see PR https://github.com/layoutBox/FlexLayout/pull/67 that rever the final change.

**Comment by Rag0n** [comment] 2018-03-06 14:14
@lucdion 
The problem is not in the final. You can add extensions even if class if final.
The problem here is that view property has internal access control.

**Comment by lucdion** [comment] 2018-03-06 14:17
Ah you're right, it just block inheriting from Flex class, which doesn't make sense

**Comment by Rag0n** [comment] 2018-03-06 14:29
@lucdion 
I have created #68 PR to change access control back to public.

**Comment by lucdion** [comment] 2018-03-06 15:23
@SirensOfTitan fixed in release https://github.com/layoutBox/FlexLayout/releases/tag/1.3.5

**Comment by SirensOfTitan** [comment] 2018-03-07 13:05
Thanks for the quick fix! 👍   I'll share my add-on code later this week when I get a chance.

**Closed** 2018-03-07 13:51 UTC
