### ISSUE TITLE
scrollview help

### ISSUE THREAD

**Issue by ChendayUP** [layoutBox/FlexLayout#111] opened 2018-09-03 10:31 UTC
I have a contentView, contentView have a scrollview, code is below, but scrollview frame is larger than contentView, not equal contentView height, how can I do?
```
addSubview(contentView)
contentView.flex.direction(.column).define { (flex) in
         flex.addItem(scrollView).define({ (flex) in
                    for item in list {
                        let view = VoteTextSelectRow(state: item)
                        flex.addItem(view).marginTop(26)
                    }
                    flex.addItem().height(80)
                })
                
        }
```

**Comment by lucdion** [comment] 2018-10-10 12:53
This is a duplicate of https://github.com/layoutBox/FlexLayout/issues/110

**Closed by lucdion** 2018-10-10 12:53 UTC
